# Use postgres/example user/password credentials
version: '3.1'

services:
  eletrotechstore_db:
    image: mysql        
    command: --default-authentication-plugin=mysql_native_password    
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: example      
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: no
    ports:
      - 8082:8080