# Use postgres/example user/password credentials
version: '3.1'

services:
  eletrotechstore_db:
    image: mysql    
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:      
      - ./docker-entrypoint-initdb.d/1.sql:/docker-entrypoint-initdb.d/1.sql
      # https://iamvickyav.medium.com/mysql-init-script-on-docker-compose-e53677102e48

  adminer:
    image: adminer
    restart: "no" 
    ports:
      - 8087:8080